#!/usr/bin/env python3
"""Run clang-tidy on CUDA sources with sanitised compile commands.

compile_commands.json generated by CMake for nvcc contains flags that
clang-tidy's Clang frontend does not understand (e.g. -Xcompiler,
--generate-code, --options-file, -forward-unknown-to-host-compiler).

This script:
  1. Reads compile_commands.json from the build directory.
  2. Strips nvcc-specific flags and rewrites the compile command for Clang.
  3. Writes a sanitised copy to <build>/tidy_db/compile_commands.json.
  4. Invokes clang-tidy with -p pointing to the sanitised database.

Usage:
  python3 cmake/run_clang_tidy.py <build_dir> <clang-tidy> <source files...>
"""

import json
import os
import re
import subprocess
import sys


# Tokens that consume the next token as an argument (two-token form).
_SKIP_NEXT = {
    "--options-file",
    "--generate-code",
    "--diag_suppress",
    "--threads",
    "-t",
    "-Xcompiler",
    "-Xptxas",
    "-Xlinker",
}

# Prefixes for single-token flags to drop.
_DROP_PREFIXES = (
    "--generate-code",
    "--options-file",
    "-forward-unknown-to-host-compiler",
    "--diag_suppress",
    "-Xcompiler",
    "-Xptxas",
    "-Xlinker",
    "-rdc=",
    "--threads",
    "-x",           # remove  -x cu  (clang infers from .cu extension)
    "-gencode",
    "-arch",
    "-code",
)


def _strip_quotes(tok: str) -> str:
    """Remove surrounding double or single quotes."""
    if len(tok) >= 2 and tok[0] == tok[-1] and tok[0] in ('"', "'"):
        return tok[1:-1]
    return tok


def _should_drop(raw_tok: str) -> bool:
    tok = _strip_quotes(raw_tok)
    return any(tok.startswith(p) for p in _DROP_PREFIXES)


def _detect_cuda_path() -> str:
    """Best-effort detection of the CUDA toolkit path."""
    for candidate in ("/usr/local/cuda", "/usr/local/cuda-13.1"):
        if os.path.isdir(candidate):
            return candidate
    return "/usr/local/cuda"


def _sanitise_command(cmd: str, cuda_path: str) -> str:
    """Rewrite an nvcc compile command for Clang's CUDA frontend."""
    tokens = cmd.split()
    out: list[str] = []
    skip_next = False
    for i, raw_tok in enumerate(tokens):
        if skip_next:
            skip_next = False
            continue
        tok = _strip_quotes(raw_tok)
        # Two-token flags.
        if tok in _SKIP_NEXT:
            skip_next = True
            continue
        # Single-token flags (with = or standalone).
        if _should_drop(raw_tok):
            # If the flag is just "-x", the next token ("cu") follows.
            if tok == "-x":
                skip_next = True
            continue
        # Drop response files (.rsp) — nvcc-specific.
        if tok.endswith(".rsp"):
            continue
        # Replace nvcc with clang++.
        if i == 0 and ("nvcc" in tok or tok == "clang++"):
            tok = "clang++"
        out.append(tok)

    # Append Clang-specific CUDA flags.
    # The compat include dir provides stub headers (e.g.
    # texture_fetch_functions.h) that CUDA 13 removed but Clang 18's
    # __clang_cuda_runtime_wrapper.h still references.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    compat_dir = os.path.join(script_dir, "clang_cuda_compat")
    cccl_dir = os.path.join(cuda_path, "include", "cccl")
    out += [
        f"--cuda-path={cuda_path}",
        "--cuda-gpu-arch=sm_86",
        "--no-cuda-version-check",
        "-xcuda",
        "-nocudalib",
        f"-isystem{compat_dir}",
        f"-isystem{cccl_dir}",
    ]
    return " ".join(out)


def main() -> int:
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <build_dir> <clang-tidy> <files...>",
              file=sys.stderr)
        return 1

    build_dir = sys.argv[1]
    clang_tidy = sys.argv[2]
    source_files = sys.argv[3:]

    cc_path = os.path.join(build_dir, "compile_commands.json")
    if not os.path.isfile(cc_path):
        print(f"Error: {cc_path} not found. "
              "Configure with CMAKE_EXPORT_COMPILE_COMMANDS=ON.", file=sys.stderr)
        return 1

    with open(cc_path) as f:
        entries = json.load(f)

    cuda_path = _detect_cuda_path()

    # Sanitise every entry.
    for entry in entries:
        if "command" in entry:
            entry["command"] = _sanitise_command(entry["command"], cuda_path)
        if "arguments" in entry:
            entry["command"] = _sanitise_command(
                " ".join(entry["arguments"]), cuda_path)
            del entry["arguments"]

    tidy_db_dir = os.path.join(build_dir, "tidy_db")
    os.makedirs(tidy_db_dir, exist_ok=True)
    tidy_cc_path = os.path.join(tidy_db_dir, "compile_commands.json")
    with open(tidy_cc_path, "w") as f:
        json.dump(entries, f, indent=2)

    cmd = [clang_tidy, "-p", tidy_db_dir, "--quiet"] + source_files
    return subprocess.call(cmd)


if __name__ == "__main__":
    sys.exit(main())
